In [1]:
import sys
sys.path.append("..")
%load_ext autoreload
%autoreload 2

In [2]:
from src.data import load_prices

In [3]:
DB_PATH = "../../financial-data-pipeline/data/market.db"

In [4]:
load_prices(DB_PATH, "SPY").head()

             adj_close
date
2014-01-02  147.831345
2014-01-03  147.807159
2014-01-06  147.378738
2014-01-07  148.283936
2014-01-08  148.316269

In [5]:
load_prices(DB_PATH, "QQQ").head()

            adj_close
date
2014-01-02  78.874672
2014-01-03  78.305305
2014-01-06  78.016083
2014-01-07  78.739098
2014-01-08  78.910820

In [6]:
load_prices(DB_PATH, "FAKE")

ValueError: No price data found for ticker FAKE

In [7]:
from src.signals import ma_signal

In [8]:
spy = load_prices(DB_PATH, "SPY")

In [14]:
spy_signal = ma_signal(spy["adj_close"])

In [15]:
spy_signal.value_counts()

adj_close
1    2307
0     895
Name: count, dtype: int64

In [16]:
type(spy_signal)

pandas.Series